import React, { useState } from 'react';
import { useAuthContext } from '../hooks/useAuthContext';
import fetchWithAuth from '../utils/fetchWithAuth';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const Reports = () => {
  const { user } = useAuthContext();
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Check if user is admin
  if (!user || user.role !== 'admin') {
    return (
      <div className="reports-container" style={{ padding: '20px', textAlign: 'center' }}>
        <h2>Access Denied</h2>
        <p>Only administrators can access reports.</p>
      </div>
    );
  }

  const generateReport = async () => {
    if (!startDate || !endDate) {
      setError('Please select both start and end dates');
      return;
    }

    if (new Date(startDate) > new Date(endDate)) {
      setError('Start date cannot be greater than end date');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetchWithAuth(`/api/reports?startDate=${startDate}&endDate=${endDate}`);

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate report');
      }

      const data = await response.json();
      console.log('Report data received:', data);
      setReportData(data);
      
      // Immediately generate and download PDF
      await generateAndDownloadPDF(data);
    } catch (error) {
      console.error('Error generating report:', error);
      setError(error.message || 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const generateAndDownloadPDF = async (reportData) => {
    if (!reportData) {
      setError('No report data available to download');
      return;
    }

    try {
      console.log('=== Starting PDF generation ===');
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Mosque Inventory Management', pageWidth / 2, 20, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont('helvetica', 'normal');
      doc.text('Inventory Report', pageWidth / 2, 30, { align: 'center' });
      
      // Report details
      doc.setFontSize(12);
      const startDateFormatted = new Date(startDate).toLocaleDateString();
      const endDateFormatted = new Date(endDate).toLocaleDateString();
      const generatedDate = new Date().toLocaleDateString();
      const generatedTime = new Date().toLocaleTimeString();
      
      doc.text(`Report Period: ${startDateFormatted} - ${endDateFormatted}`, 20, 45);
      doc.text(`Generated on: ${generatedDate} at ${generatedTime}`, 20, 55);
      doc.text(`Generated by: ${user.name || 'Admin'}`, 20, 65);

      let yPosition = 80;

      // Summary Section
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      
      // Manual summary table (without autoTable dependency)
      const summaryLines = [
        `Total Items: ${reportData.inventory?.totalItems || 0}`,
        `Low Stock Items: ${reportData.inventory?.lowStockItems || 0}`,
        `Total Stock Value: $${(reportData.inventory?.totalValue || 0).toFixed(2)}`
      ];
      
      summaryLines.forEach(line => {
        doc.text(line, 30, yPosition);
        yPosition += 8;
      });
      
      yPosition += 10;

      // Inventory Items Section
      if (reportData.inventory?.items && reportData.inventory.items.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Inventory Items', 20, yPosition);
        yPosition += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        
        // Column headers
        const colX = { name: 20, sku: 65, type: 95, qty: 130, rate: 160 };
        doc.text('Item Name', colX.name, yPosition);
        doc.text('SKU', colX.sku, yPosition);
        doc.text('Type', colX.type, yPosition);
        doc.text('Qty', colX.qty, yPosition);
        doc.text('Rate', colX.rate, yPosition);
        yPosition += 8;
        
        // Draw line
        doc.setDrawColor(200);
        doc.line(20, yPosition - 2, 200, yPosition - 2);
        
        // Data rows
        doc.setFont('helvetica', 'normal');
        reportData.inventory.items.forEach(item => {
          if (yPosition > 250) {
            doc.addPage();
            yPosition = 20;
          }
          
          const name = (item.name || 'N/A').substring(0, 20);
          const sku = (item.sku || 'N/A').substring(0, 10);
          const type = (item.type || 'N/A').substring(0, 10);
          const qty = (item.quantity || 0).toString();
          const rate = `$${(item.rate || 0).toFixed(2)}`;
          
          doc.text(name, colX.name, yPosition);
          doc.text(sku, colX.sku, yPosition);
          doc.text(type, colX.type, yPosition);
          doc.text(qty, colX.qty, yPosition);
          doc.text(rate, colX.rate, yPosition);
          yPosition += 8;
        });
      }

      // Generate PDF file name
      const fileName = `mosque_inventory_report_${startDate}_${endDate}.pdf`;
      console.log('PDF file name:', fileName);
      
      // Download PDF to user's computer
      console.log('Saving PDF to downloads...');
      doc.save(fileName);
      console.log('PDF save() called');

      // Now convert to base64 and save to backend
      const pdfBlob = doc.output('blob');
      console.log('PDF blob size:', pdfBlob.size);
      
      const reader = new FileReader();
      reader.onload = async () => {
        try {
          const result = reader.result;
          const base64data = result.split(',')[1];
          console.log('Converted to base64, length:', base64data.length);

          // Save document to backend
          console.log('POSTing document to /api/documents...');
          const saveResponse = await fetchWithAuth('/api/documents', {
            method: 'POST',
            body: JSON.stringify({
              title: `Inventory Report ${startDateFormatted} to ${endDateFormatted}`,
              fileName: fileName,
              fileData: base64data,
              fileSize: pdfBlob.size,
              type: 'report',
              description: `Generated inventory report for period ${startDateFormatted} to ${endDateFormatted}`,
              metadata: {
                reportType: 'inventory',
                dateRange: { startDate, endDate },
                summary: reportData.inventory || {}
              }
            })
          });

          console.log('POST response received, status:', saveResponse.status);
          
          if (saveResponse.ok) {
            const savedDoc = await saveResponse.json();
            console.log('✅ Report saved successfully:', savedDoc.id);
            // Emit event to notify Documents page to refresh
            window.dispatchEvent(new CustomEvent('document-saved', { detail: { title: `Inventory Report ${startDateFormatted} to ${endDateFormatted}` } }));
            setError('');
          } else {
            console.warn('❌ Save failed with status:', saveResponse.status);
            const errorText = await saveResponse.text();
            console.warn('Error response:', errorText);
            setError(`Failed to save to documents (${saveResponse.status})`);
          }
        } catch (err) {
          console.error('❌ Error in FileReader.onload:', err);
          setError(`Error saving document: ${err.message}`);
        }
      };
      
      reader.onerror = (error) => {
        console.error('FileReader error:', error);
        setError('Failed to read PDF file');
      };

      console.log('Starting FileReader conversion...');
      reader.readAsDataURL(pdfBlob);
      
    } catch (error) {
      console.error('❌ Error generating PDF:', error);
      setError('Failed to generate PDF: ' + error.message);
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  const formatCurrency = (amount) => {
    return `$${parseFloat(amount).toFixed(2)}`;
  };

  return (
    <div className="reports-container" style={{ 
      padding: '20px',
      maxWidth: '1200px',
      margin: '0 auto'
    }}>
      <div style={{
        background: 'white',
        borderRadius: '12px',
        padding: '30px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)'
      }}>
        <h1 style={{ 
          fontSize: '28px', 
          fontWeight: 'bold', 
          color: '#2d3748',
          marginBottom: '10px'
        }}>
          📊 Inventory Reports
        </h1>
        <p style={{ color: '#718096', fontSize: '16px', marginBottom: '30px' }}>
          Generate inventory reports for any date range
        </p>

        {/* Date Range Selection */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
          gap: '20px',
          marginBottom: '20px'
        }}>
          <div>
            <label style={{
              display: 'block',
              marginBottom: '8px',
              fontWeight: '600',
              color: '#374151'
            }}>
              Start Date
            </label>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              style={{
                width: '100%',
                padding: '10px',
                border: '1px solid #d1d5db',
                borderRadius: '6px',
                fontSize: '14px'
              }}
            />
          </div>

          <div>
            <label style={{
              display: 'block',
              marginBottom: '8px',
              fontWeight: '600',
              color: '#374151'
            }}>
              End Date
            </label>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              style={{
                width: '100%',
                padding: '10px',
                border: '1px solid #d1d5db',
                borderRadius: '6px',
                fontSize: '14px'
              }}
            />
          </div>
        </div>

        {/* Error Display */}
        {error && (
          <div style={{
            backgroundColor: '#fee2e2',
            border: '1px solid #fecaca',
            color: '#991b1b',
            padding: '12px',
            borderRadius: '6px',
            marginBottom: '20px'
          }}>
            {error}
          </div>
        )}

        {/* Action Buttons */}
        <div style={{ display: 'flex', gap: '12px', marginBottom: '30px' }}>
          <button
            onClick={generateReport}
            disabled={loading}
            style={{
              padding: '12px 24px',
              backgroundColor: loading ? '#9ca3af' : '#3b82f6',
              color: 'white',
              border: 'none',
              borderRadius: '6px',
              fontSize: '16px',
              fontWeight: '600',
              cursor: loading ? 'not-allowed' : 'pointer'
            }}
          >
            {loading ? 'Generating...' : 'Generate Report & Download'}
          </button>
        </div>

        {/* Report Display */}
        {reportData && (
          <div style={{
            marginTop: '30px',
            padding: '20px',
            backgroundColor: '#f9fafb',
            borderRadius: '8px',
            border: '1px solid #e5e7eb'
          }}>
            <h2 style={{ 
              fontSize: '22px', 
              fontWeight: 'bold', 
              marginBottom: '20px',
              color: '#1f2937'
            }}>
              Report Summary
            </h2>

            {/* Summary Cards */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '15px',
              marginBottom: '30px'
            }}>
              <div style={{
                backgroundColor: 'white',
                padding: '20px',
                borderRadius: '8px',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
              }}>
                <h3 style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>
                  Total Items
                </h3>
                <p style={{ fontSize: '28px', fontWeight: 'bold', color: '#1f2937', margin: 0 }}>
                  {reportData.inventory?.totalItems || 0}
                </p>
              </div>

              <div style={{
                backgroundColor: 'white',
                padding: '20px',
                borderRadius: '8px',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
              }}>
                <h3 style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>
                  Low Stock Items
                </h3>
                <p style={{ fontSize: '28px', fontWeight: 'bold', color: '#ef4444', margin: 0 }}>
                  {reportData.inventory?.lowStockItems || 0}
                </p>
              </div>

              <div style={{
                backgroundColor: 'white',
                padding: '20px',
                borderRadius: '8px',
                boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
              }}>
                <h3 style={{ fontSize: '14px', color: '#6b7280', marginBottom: '8px' }}>
                  Total Value
                </h3>
                <p style={{ fontSize: '28px', fontWeight: 'bold', color: '#10b981', margin: 0 }}>
                  {formatCurrency(reportData.inventory?.totalValue || 0)}
                </p>
              </div>
            </div>

            {/* Inventory Items Table */}
            {reportData.inventory?.items && reportData.inventory.items.length > 0 && (
              <div>
                <h3 style={{ 
                  fontSize: '18px', 
                  fontWeight: 'bold', 
                  marginBottom: '15px',
                  color: '#1f2937'
                }}>
                  📦 Inventory Items
                </h3>
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ 
                    width: '100%', 
                    borderCollapse: 'collapse',
                    backgroundColor: 'white',
                    borderRadius: '8px',
                    overflow: 'hidden'
                  }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f3f4f6' }}>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #e5e7eb' }}>Item Name</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #e5e7eb' }}>SKU</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid #e5e7eb' }}>Type</th>
                        <th style={{ padding: '12px', textAlign: 'right', borderBottom: '2px solid #e5e7eb' }}>Quantity</th>
                        <th style={{ padding: '12px', textAlign: 'right', borderBottom: '2px solid #e5e7eb' }}>Rate</th>
                        <th style={{ padding: '12px', textAlign: 'right', borderBottom: '2px solid #e5e7eb' }}>Value</th>
                      </tr>
                    </thead>
                    <tbody>
                      {reportData.inventory.items.map((item, index) => (
                        <tr key={index} style={{ borderBottom: '1px solid #f3f4f6' }}>
                          <td style={{ padding: '12px' }}>{item.name}</td>
                          <td style={{ padding: '12px' }}>{item.sku || 'N/A'}</td>
                          <td style={{ padding: '12px' }}>
                            <span style={{
                              backgroundColor: '#f3f4f6',
                              padding: '4px 8px',
                              borderRadius: '4px',
                              fontSize: '12px'
                            }}>
                              {item.type}
                            </span>
                          </td>
                          <td style={{ padding: '12px', textAlign: 'right' }}>{item.quantity}</td>
                          <td style={{ padding: '12px', textAlign: 'right' }}>{formatCurrency(item.rate)}</td>
                          <td style={{ padding: '12px', textAlign: 'right', fontWeight: '600' }}>
                            {formatCurrency(item.quantity * item.rate)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default Reports;
